#!/usr/bin/env ruby

require 'delayed_job_sequel'

Sequel.connect(ENV.fetch('DB'))
::Delayed::Worker.backend = :sequel

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'newsletter/job'

addresses = ARGV.dup.uniq
ARGV.clear

job = Newsletter::Job.new(ARGF.read.chomp, addresses)
::Delayed::Job.enqueue(job)
